#ifndef DILLO_PROTOS_H
#define DILLO_PROTOS_H

/*
**  dillo_protos.h - Header file for armadillo.library code modules
**                   © Copyright 1993-1999, Amiga, Inc.
**                   All Rights Reserved.
**                   Generated by SAS/C 6.2 (Modified by JFW)
**
**  Function prototypes for all of the functions in the library.  Used
**  to keep SAS/C docile.
**
*/

struct Armadillo * __asm __saveds CreateArmadillo(void);
void __asm __saveds DeleteArmadillo(register __a0 struct Armadillo * );
BOOL __asm __saveds NameArmadillo(register __a0 struct Armadillo * ,
                                  register __a1 STRPTR ,
                                  register __d0 ULONG );
BOOL __asm __saveds FillArmadillo(register __a0 struct Armadillo * ,
                                  register __d0 ULONG );
BOOL __asm __saveds FlattenArmadillo(register __a0 struct Armadillo * ,
                                     register __d0 BOOL );
BOOL __asm __saveds DilloFlat(register __a0 struct Armadillo * );
ULONG __asm __saveds DilloWeight(register __a0 struct Armadillo * );
BOOL __asm __saveds DilloName(register __a0 struct Armadillo * ,
                              register __a1 STRPTR ,
                              register __d0 ULONG );
void __asm __saveds ClearDillo(register __a0 struct Armadillo * );
ULONG __asm __saveds DilloBirths(void);

#endif /* DILLO_PROTOS_H */